// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Execute a Bless Function
	// (POST /api/v1/functions/execute)
	ExecuteFunction(ctx echo.Context) error
	// Execute a Bless Function with a batch of arguments
	// (POST /api/v1/functions/execute/batch)
	ExecuteFunctionBatch(ctx echo.Context) error
	// Get the result of a Batch Execution Request
	// (POST /api/v1/functions/execute/batch/result)
	BatchExecutionResult(ctx echo.Context) error
	// Install a Bless Function
	// (POST /api/v1/functions/install)
	InstallFunction(ctx echo.Context) error
	// Get the result of an Execution Request
	// (POST /api/v1/functions/requests/result)
	ExecutionResult(ctx echo.Context) error
	// Check Node health
	// (GET /api/v1/health)
	Health(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ExecuteFunction converts echo context to params.
func (w *ServerInterfaceWrapper) ExecuteFunction(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ExecuteFunction(ctx)
	return err
}

// ExecuteFunctionBatch converts echo context to params.
func (w *ServerInterfaceWrapper) ExecuteFunctionBatch(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ExecuteFunctionBatch(ctx)
	return err
}

// BatchExecutionResult converts echo context to params.
func (w *ServerInterfaceWrapper) BatchExecutionResult(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.BatchExecutionResult(ctx)
	return err
}

// InstallFunction converts echo context to params.
func (w *ServerInterfaceWrapper) InstallFunction(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.InstallFunction(ctx)
	return err
}

// ExecutionResult converts echo context to params.
func (w *ServerInterfaceWrapper) ExecutionResult(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ExecutionResult(ctx)
	return err
}

// Health converts echo context to params.
func (w *ServerInterfaceWrapper) Health(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Health(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/api/v1/functions/execute", wrapper.ExecuteFunction)
	router.POST(baseURL+"/api/v1/functions/execute/batch", wrapper.ExecuteFunctionBatch)
	router.POST(baseURL+"/api/v1/functions/execute/batch/result", wrapper.BatchExecutionResult)
	router.POST(baseURL+"/api/v1/functions/install", wrapper.InstallFunction)
	router.POST(baseURL+"/api/v1/functions/requests/result", wrapper.ExecutionResult)
	router.GET(baseURL+"/api/v1/health", wrapper.Health)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbWXPbOPL/Kij+/4+UZMtXjd8cx9m4NpN47dmkdqdcGpBskohIgAFA2UpK330LBy+R",
	"um3LmcqTLRAEGt2/vsEfjs/SjFGgUjjnPxzhx5Bi/e9FFHGIsITgFkSeSDUWgPA5ySRh1Dl3zDhiIcIU",
	"XT2Cn6sH6Ba+5SCk4zoZZxlwSUAvGHL1gPrT9krvikdqMRkTgbhZG6eMRggnCaIsAIFkjCUCvRUESMaA",
	"eLkbPOI0S8A5P+ifnrqOnGbgnDs0Tz3gjus89iLWs4NhwrA8Pa6P9sSYZD2mKcJJL2OESuDOueQ5zFwn",
	"A+CiTfgH4mXDDF2/FYZyQB8rOiMm64epk/inczh8e/RPxr7cZkcXn8dn36Q/vJicPpJv0cV3fPhflo/F",
	"v/B//LuhP/n42/H4/d0lw467zWuec+86REKq6bccEJITGjmzkk+YczzdgCG8BMX/cwidc+f/BhWUBhZH",
	"gxIVFkOzakPmfQVfzgkGF6Dr3xY8qwgiaca43jLDMnbOnYjIOPf6PksHXgJCUJAPjI8H3pkYKLwMyuXU",
	"Qdc92TzwO8UuNO5zSr7lYOVbQqBLFUr+L+NWS+WWiKeDWWIv3JKSEy+XcCElCMm6tESxgXBAIgOfhMRH",
	"uJiLsEATlvux0q55gwHYjztV7mZ4g24AeKF3aiJKMQ2wZHxarl5n+/4076kUjlEYsXAtflTsfYiBA3ow",
	"ZlKJAEuUAFbopfB3Mkgr7Ip1Gf0OtG6tMykLIBEDu/QmOvMGSz+umUZjJNSuDfxjHuVp4ZmbQr/8cI3K",
	"xyhkXBueN4pE9C6nvp5WF++fTq+HeeS4Tki4kD1CJ8zHalqvWMdxHSZj4NXC/X7fuXerVwX4jAbbvStj",
	"wjd5tQ6RNbGyvW5JSLNEGb4VBvoPO68lO7UGy4jfltQ11aIRPlDMCSs0kvExcC25FIncizjLM+GiKcuR",
	"jymSmEcgEa5MZjEJeVM7OCU0QkQKRAKgkoREhzlNFm2gPtZCBMoWlPxwayC8n1exDiSLjFEBbSj7cU7H",
	"BtRBQAwJN40Zy9h+qd4ufNzM7QxDS+8Lpfe1A5rGwhW7VfToTVFAwhA4UGnCyw0Q47MA2sK+k1jmJSWe",
	"3rikp66PzvDgYGthuU4KQuCog4Dr+pFbcQgKMUkgcE1UahdBKYliiWI8AZQyDojQkCHssVwafnLO+A60",
	"2gB9RIIOct8ui5kqbnmnoef5J9A7DA5Pe8eAf+t5JydnvZPD8BifYu/k9MTfBfvduDbAqpnnJvH/AGkz",
	"kFoatIDzbqWkGni1zAVdv21FPst5tWCPF+VY3VqQoG0b1sdHQ7lbhkPlXct4oZ6jh5jVk0IiGqzYMrDZ",
	"Hu/lURbZOrt0p63Twi1ceCsN2JC7K6Iibu11XyWtDTnsGhQVK+uEr0TqJaMhiTqiGT2ec2zMth6uoprV",
	"lQVcRHUrPYk66EU1WxtyKoCKXIxwEjFOZJy2CfwSEz9G5VRUTkUiZnkSIA+0K4fAUk3EArufeaHcAVxA",
	"J6MJ7sqxruiEcEaVq0YTzAlWolkcGa6Vj37EKQSfcZLDDrGVKcCMWDgyPrZF+Uc9QSl0rcZj+Wq1ekV0",
	"e1gSp7aOmuWelYUdnhIhFOLapN1UD9tw7EwvnVjKTJwPBjgjfTuqNMVxn7jyMiqydU3pcjkarb6ovaCW",
	"yakk6cqQ99ZMs6o7cx0hA0I7Qx8aYB6ga5rlco2UZO03ttUVGXMQMUs6fOkN4/UIsY07Y78C9EBkjHDh",
	"4iXTNoAEMK/jSOS+D0KEedINzHYZchX1JAWWd4Qd79kDShiNClKbMa/EY3C2Voc1s2gLhj1kzqXy3WCO",
	"U5AmOGh6g4k2WK1sccvgxqx2vx5jKqr2yZtXXlB4jmq0X0YWa1WjK2sW2rN1pieXVZwZdlkwD4dTDwge",
	"Hk+O/e94IrOvk6HPjr6eHLNjfPJdBvk3P5tOCQX+NaL+45kYiuFQnAHeKfmTMeugVnnrgtwvF3e/o5Ak",
	"oGxWgaU66TEkCes9MJ4E/Qcs0h3oyQrQW1hlHHwslfaoCXXMlLrp9Hp+QnphgqNDZ+ZW4/pvc6iaOmxP",
	"HTqz+zWDmQ7T0YW3iv4eByw0Z/8tTATyVwnkv1BIIAn6mxj011EfqiDwVOlfXYVKdO6QEK5TTkpyYW3/",
	"qmj/0k5ds2azj2rNrzrN5qn1Jm00sbztuAEcO9vgF77McYJYLrO8owzpooSMAZXR7ic9z60GrpTgXHT1",
	"SCS6ZAEgkH6/3+6GPRI56oawflU96kLxtswWMgDOlwT6mu4n3rEz4p1j3dNtuWa4a1Mgs/s+IrsiALum",
	"QuIkWRjf+T9PELPYG+Kfyhe6Ts5JswLwVH7V362u2gLNQmdqbcrTuLvZ7hRvU3d/3or736XWPs/hX/HV",
	"r/hq3/HVe8CJjA1KOpJaFdUI89B9rYarVidvR4doDNOeTlZRhglvnYLidO4UemR7KZb1r2pFM/REJsiS",
	"t1Fh7IpOPuO9VMXmOj5t+ZTPTAG4ZqRohAz8TKFVWYau1hMoeKr8t2JSS78FIhJR8JWp4dNqJ71+1b5C",
	"mIO9D2c6Sd5UObfahbZSpiFOBJTM9xhLANMNUILr1/WWanv7ylQBMsOBJPkU6uLOasa22Dlzf6xL8fqt",
	"qvuNb4OJfSHzsnK084GwCndNQ7TyQdYvz/XKGq3v2oXoJlJT3NW2sbcHKwd0w0mqIKrWL+vARTywx7b6",
	"4gvYhv65C9iEGm5UlO/7KuhWr/lPd4N03d5OybAXV4h2m7IVmALFXlJv7mxu+Jrl6k3b3z+eudTQYsE+",
	"5NBo+W54W8O0jOwSLSMUgJdHIxVZ7yTDgJMJcDHijMmR4cWPHe5USD6da+I/XXckzCGpUbf5BYWERZHx",
	"ENvnRynjHV/d/K7HUUJSIrvvrWxNNM/pqLhd8Ora128+3DUhvgcdW3iTuKM886u1uZ/W5rP2udTq8CiB",
	"U5y8ZX5HaPOO0ACpyE9XI0wQePeAI6MROU/sbaPzwUCY4T5hSvCFeW0u94dSbiLQm7M79B5wYILxO+AT",
	"4MjDAgLETC/yUwb04uYaHfUPypqqNvZ9xUoiNZfVMnqFWxASqem9+osqQQQuzNYH/eP+b4oylgHFGXHO",
	"naP+Qf9IuQcsY332Ac7IYHI4KLhcaZXSCNZVCLyyl8Nw+56CUiBN8nVQTaw9t0HyGxZMrY5JoHoLnGWJ",
	"Pe7gqzAxiFGyDb51sx8FzFp31ZeQXEGtqsbo8pxmz/Dg4DkILW9ptii9Ky801TzCzHWODSHz2coEJySo",
	"GXJefRhx0v2GgT4SBoCmuqbIEHmqEpDlzJI4EnWdFI5O+haCaKDv4m8OpeIC2ANRebqKt3W9ubxHswJp",
	"+jLvM8Gt+yOiDTBnvk94UeQt+Fzk54JfgQnzecccHLYD5qD6mrYbnx09jyWfATQx2WK6+a722TDZbN/M",
	"mm709SBsnn2WtRwkJzCBYCXangJjm8l1bXAR0/NbjCfbFFztOu3EZ3adCxrcHVJbQvjLgWxRa3Uxvbhu",
	"lRD2x5Q9JBBECmYNQCw539rSt9uIbawKXcOgvIwt6e4Gv7A5WdAwXehlX5MhodvYkFh34xQNEXQg5jIG",
	"f2zifjtzHhzvi+Fnk0mjYdghCU0dEZbA6Ryjuk5Q8MQO3OtF7WArUpwAn8qY0MimZE09NZ+erZ3WNRI5",
	"cT4wJYZ+UWMImC8G9oeCh+kV1mQ3c+eX/wychLZ8b86DMA0QnmCSYI8kRE6dciF74Nn97H8BAAD//9s1",
	"YgUJRgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
